Update dep review workflow

diff --git a/.github/workflows/dependency-review.yml b/.github/workflows/dependency-review.yml
--- a/.github/workflows/dependency-review.yml
+++ b/.github/workflows/dependency-review.yml
@@ -19,20 +19,20 @@ jobs:
         uses: actions/checkout@v3.0.2
 
       - name: GitHub dependency vulnerability check
-        if: ${{ github.event_name == 'pull_request_target' }}
+        if: ${{ github.event_name == 'pull_request' }}
         uses: WillDaSilva/dependency-review-action@v2.1.0
 
-      - name: FOSSA dependency license check
-        run: |
-          curl --no-progress-meter -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/v${FOSSA_CLI_VERSION}/install-latest.sh | bash
+      # - name: FOSSA dependency license check
+      #   run: |
+      #     curl --no-progress-meter -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/v${FOSSA_CLI_VERSION}/install-latest.sh | bash
 
-          echo '## FOSSA dependency license check' >> $GITHUB_STEP_SUMMARY
-          echo '' >> $GITHUB_STEP_SUMMARY
+      #     echo '## FOSSA dependency license check' >> $GITHUB_STEP_SUMMARY
+      #     echo '' >> $GITHUB_STEP_SUMMARY
 
-          fossa analyze --revision ${{ github.sha }} --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }} |& tee fossa_analyze.log
-          fossa test --revision ${{ github.sha }} --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }}
+      #     fossa analyze --revision ${{ github.sha }} --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }} |& tee fossa_analyze.log
+      #     fossa test --revision ${{ github.sha }} --fossa-api-key ${{ secrets.MELTYBOT_FOSSA_API_KEY }}
 
-          TEST_FAILED=$?
-          FOSSA_REPORT_LINK="$(grep -A 1 '[ INFO] View FOSSA Report:' fossa_analyze.log | tail -n 1 | sed -e 's/^\[ INFO\]\s*//')"
-          echo "[FOSSA detected $([ $TEST_FAILED -ne 0 ] && echo -n '' || echo 'no ')issues](${FOSSA_REPORT_LINK})" >> $GITHUB_STEP_SUMMARY
-          exit $TEST_FAILED
+      #     TEST_FAILED=$?
+      #     FOSSA_REPORT_LINK="$(grep -A 1 '[ INFO] View FOSSA Report:' fossa_analyze.log | tail -n 1 | sed -e 's/^\[ INFO\]\s*//')"
+      #     echo "[FOSSA detected $([ $TEST_FAILED -ne 0 ] && echo -n '' || echo 'no ')issues](${FOSSA_REPORT_LINK})" >> $GITHUB_STEP_SUMMARY
+      #     exit $TEST_FAILED
